[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_DECERNIS_API_BASE_URL = "/.netlify/functions/decernis-proxy"
  NODE_VERSION = "20"
  NPM_VERSION = "9.9.3"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[[redirects]]
  from = "/decernis-api/*"
  to = "/.netlify/functions/decernis-proxy/:splat"
  status = 200
